### ISSUE TITLE
How to prevent swap between two dropzones?

### ISSUE THREAD

**Issue by gaffkins** [Postlagerkarte/blazor-dragdrop#27]
Because set AllowSwap on booth to false dosn't work.

**Comment by Postlagerkarte** [comment]
Hi @gaffkins 

AllowSwap is relevant if the MaxItem Limit of a dropzone has been reached.  
 
If AllowSwap is false and MaxItem Limit has been reached you can not drag a new item to that dropzone. You need to move away a item from that dropzone before you can drop another item.

If AllowSwap is true and MaxItem Limit has been reached you can drag a new item to that dropzone however an existing item will be removed so that MaxItemLimit is still respected. The item that is removed is swapping places with the new item.

**Comment by gaffkins** [comment]
Thank you. With your tips I resolve this with AllowSwap=false and MaxItemsLimit=0.
Best!
