### ISSUE TITLE
Referenced Microsoft Packages fail to update from v3.1.x to v5.0.x

### ISSUE THREAD

**Issue by DoomerDGR8** [Postlagerkarte/blazor-dragdrop#94]
I cannot update this library to v5.0.2:

![image](https://user-images.githubusercontent.com/825078/105806481-859c4200-5fbd-11eb-94e0-a9bdf3516e7c.png)

Package Microsoft.AspNetCore.Components 5.0.2 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1).
Package Microsoft.AspNetCore.Components 5.0.2 supports: net5.0 (.NETCoreApp,Version=v5.0)
Plk.Blazor.DragDrop

Package Microsoft.AspNetCore.Components.Web 5.0.2 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1).
Package Microsoft.AspNetCore.Components.Web 5.0.2 supports: net5.0 (.NETCoreApp,Version=v5.0)
Plk.Blazor.DragDrop

Is this issue from Microsoft?

**Comment by vkristijan** [comment]
According to the error message, you were trying to update the two packages while using an older version of .net (netstandard2.1). This is not supported and in order to update the packages you also need to update the .net version. 

This has been done. Both the .net version and package versions were updated in  this PR #134 
@Postlagerkarte can you close this issue?
